source 'https://github.com/CocoaPods/Specs.git'

target 'PXTutorialManager', :exclusive => true do
  pod "PXTutorialManager", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PXTutorialManager", :path => "../"


end
